server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:buaamapforum.cn.jks
    key-store-type: JKS
    key-store-password: ENC(AFimlFPLVzi0KrUhTGH14/lbochjLvNf9Da61U2OTxQqcttKZ/2GFaRzBeRofj9H)

condition:
  http2https: true

http:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://43.143.148.116:3306/buaa_map
    username: ENC(shfsyz9tI2sZv7Ij6w6pDZcgiTDxrCzGqgy9vc65IrL+nApBDFrGm6psipffDW8R)
    password: ENC(GHkX3pTrfc6P2V6MAdjoRsRuq58tV3hLmhjN68dbhQgNmE1iGAybCIg52ZhbdhrJ5KpgaEZ7uX6haX48PQWmVg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: buaamap@163.com
    email: buaamap@163.com
    password: ENC(CtG7TZIdZYeYucZGVX1mwMIWPH2jWxgxGeUZjmxqTdoMnGUWnrM1nMGjRHM7RmfcsyRQaZMwqyW6oM2XO4YsHw==)
    host: smtp.163.com
    port: 465
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  data:
    redis:
      host: 43.143.148.116
      port: 6379
      password: ENC(LamOVZqZQDZM0dXAUIYKxZlGe96rZ9MY6VLa6YOMpJoSirLILfVzLAJpN7KLxKDP)
  tengxun:
    accessKey: ENC(/yxxYVe8H8qqpMPwPp9W7rRdnj5i9GpuKbjfD2ugXe/JNgUF5rWwQbdjlZGP9OsT3vyG61JAUyURB1/fFbJXgemuJ07TpMsRKw1lgA+ZJX0=)
    secretKey: ENC(oMG76T9mpVozeD2xRS+ftnQaqEp+6VE5gSgNRB8iEcaTk0hgy45jvesfr7BXjj+QmS0n4TJxRqQ6DEFNMLNLjlp1Vz0rscZY/WfaR9OBOF0=)
    bucket: ap-beijing
    bucketName: agile-pic-1313874439
    path: https://agile-pic-1313874439.cos.ap-beijing.myqcloud.com
  servlet:
    multipart: #设置文件上传大小
      max-file-size: 10MB  # 最大文件大小
      max-request-size: 10MB  # 最大请求大小
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# 验证码
code:
  expiration: 300

# 用户默认信息
info:
  default_description: "介绍一下自己吧~"

# token相关
jwt:
  key: ENC(jCoJj4mmCaHXorPnhbkGb4SPNeYwNNLAVv16Jfa8O03egFbGj9W3DYl8s7atDDXtY0cUh0q9B1CLUbEPNWRGVg==)
  # token有效时间为一小时
  expiration: 7200

logging:
  file:
    path: ${user.dir}/logs/

# 用户每日各任务最大次数
times:
  report: 10
  feedback: 5
  apply: 3
