server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://43.143.148.116:3306/buaa_map
    username: ENC(shfsyz9tI2sZv7Ij6w6pDZcgiTDxrCzGqgy9vc65IrL+nApBDFrGm6psipffDW8R)
    password: ENC(QorDisAy731EOQ48NzZlr2oQepqFb325bakd64M5NYU9hwygS6++oSeo1uBfD1hEKBCz/GnSfoaEu8/fbOoE4A==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: buaamap@163.com
    email: buaamap@163.com
    password: ENC(CtG7TZIdZYeYucZGVX1mwMIWPH2jWxgxGeUZjmxqTdoMnGUWnrM1nMGjRHM7RmfcsyRQaZMwqyW6oM2XO4YsHw==)
    host: smtp.163.com
    port: 25
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  data:
    redis:
      host: 43.143.148.116
      port: 6379
      password: ENC(LamOVZqZQDZM0dXAUIYKxZlGe96rZ9MY6VLa6YOMpJoSirLILfVzLAJpN7KLxKDP)

code:
  expiration: 300

info:
  default_description: "阳光开朗大男孩"

jwt:
  key: ENC(jCoJj4mmCaHXorPnhbkGb4SPNeYwNNLAVv16Jfa8O03egFbGj9W3DYl8s7atDDXtY0cUh0q9B1CLUbEPNWRGVg==)
  expiration: 1000